obj_player.attemptsOutOfBed = 0;
//obj_player.x = 64;
//obj_player.y = 448;
obj_player.canMove = false;
obj_player.lost = false;
obj_player.leftBed = false;
obj_player.startedSleeping = false;
obj_player.sprite_index = Idle_Noah
obj_game_controller.classHappened= false;